"""The profile-picture pack: the library the phone downloads, and the art behind it.

static/data/teams.json is generated by scripts/build_team_library.py and shipped to the
browser, where <Avatar> trusts it completely: it renders whatever `bg` says on whatever
`cut` says without checking anything. So the checking happens here.
"""
from __future__ import annotations

import json
import os
import re
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

LIBRARY = os.path.join(ROOT, "static", "data", "teams.json")
EXTRA = os.path.join(ROOT, "inputs", "extra_teams.json")
LOGO_DIR = os.path.join(ROOT, "static", "logos")
HEX = re.compile(r"^#[0-9a-f]{6}$")


def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def library():
    assert os.path.exists(LIBRARY), "run python scripts/build_team_library.py"
    return read_json(LIBRARY)


def test_the_library_holds_every_school(library):
    assert len(library) >= 139, "expected the 138 FBS schools plus the extras"


def test_the_library_matches_a_fresh_build(library):
    """It is generated. A hand edit, or a stale copy after a logo changes, is the bug."""
    import build_team_library as builder

    fresh, _stats, missing = builder.build()
    assert not missing, "logos missing for %s" % missing[:5]
    assert library == fresh, (
        "static/data/teams.json is stale. Rebuild it with "
        "python scripts/build_team_library.py")


def test_every_team_has_the_cut_of_its_mark_that_was_chosen(library):
    """`cut` names a file. If that file is not there the avatar is an empty disc."""
    for t in library:
        name = "%s-dark.png" % t["id"] if t["cut"] == "dark" else "%s.png" % t["id"]
        assert os.path.exists(os.path.join(LOGO_DIR, name)), \
            "%s wants %s, which is not on disk" % (t["school"], name)


def test_every_background_is_a_real_colour(library):
    """<Avatar> puts this straight into a style attribute."""
    for t in library:
        assert HEX.match(t["bg"]), "%s has bg %r" % (t["school"], t["bg"])
        assert t["cut"] in ("light", "dark"), "%s has cut %r" % (t["school"], t["cut"])


def test_every_id_survives_the_format_check_in_sql(library):
    """set_my_team rejects anything else, so an id it refuses is unpickable."""
    ok = re.compile(r"^[A-Za-z0-9_-]{1,16}$")
    for t in library:
        assert ok.match(t["id"]), "%s has id %r, which set_my_team would reject" % (
            t["school"], t["id"])


def test_no_two_schools_share_an_id(library):
    ids = [t["id"] for t in library]
    assert len(ids) == len(set(ids))


# ------------------------------------------------------------------ the extras

def test_georgia_college_is_in_the_pack(library):
    """Grant's alma mater, and the reason the extras pipeline exists at all.

    It is Division II Peach Belt with no football team, so it is in none of ESPN's lists
    and nothing else in the build would notice if it disappeared.
    """
    gc = [t for t in library if t["id"] == "gcsu"]
    assert gc, "Georgia College is missing from the library"
    assert gc[0]["mascot"] == "Bobcats"
    assert gc[0]["bg"] == "#001e78", (
        "the bobcat is outlined in the school green and vanishes on green; it was put on "
        "the school navy on purpose")


def test_every_extra_school_records_where_its_mark_came_from():
    """These are copyrighted school marks. The basis for using them is not optional."""
    for t in read_json(EXTRA):
        for field in ("source", "source_page", "license"):
            assert t.get(field), "%s has no %s" % (t["id"], field)
        assert t["source"].startswith("https://"), t["id"]
