"""The profile-picture pack: the library the phone downloads, and the art behind it.

static/data/teams.json is generated by scripts/build_team_library.py and shipped to the
browser, where <Avatar> trusts it completely: it renders whatever `bg` says on whatever
`cut` says without checking anything. So the checking happens here.
"""
from __future__ import annotations

import json
import os
import re
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

LIBRARY = os.path.join(ROOT, "static", "data", "teams.json")
EXTRA = os.path.join(ROOT, "inputs", "extra_teams.json")
LOGO_DIR = os.path.join(ROOT, "static", "logos")
HEX = re.compile(r"^#[0-9a-f]{6}$")


def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def library():
    assert os.path.exists(LIBRARY), "run python scripts/build_team_library.py"
    return read_json(LIBRARY)


def test_the_library_holds_every_school(library):
    assert len(library) >= 139, "expected the 138 FBS schools plus the extras"


def test_the_library_matches_a_fresh_build(library):
    """It is generated. A hand edit, or a stale copy after a logo changes, is the bug."""
    import build_team_library as builder

    fresh, _stats, missing = builder.build()
    assert not missing, "logos missing for %s" % missing[:5]
    assert library == fresh, (
        "static/data/teams.json is stale. Rebuild it with "
        "python scripts/build_team_library.py")


def test_every_team_has_the_cut_of_its_mark_that_was_chosen(library):
    """`cut` names a file. If that file is not there the avatar is an empty disc."""
    for t in library:
        name = "%s-dark.png" % t["id"] if t["cut"] == "dark" else "%s.png" % t["id"]
        assert os.path.exists(os.path.join(LOGO_DIR, name)), \
            "%s wants %s, which is not on disk" % (t["school"], name)


def test_every_background_is_a_real_colour(library):
    """<Avatar> puts this straight into a style attribute."""
    for t in library:
        assert HEX.match(t["bg"]), "%s has bg %r" % (t["school"], t["bg"])
        assert t["cut"] in ("light", "dark"), "%s has cut %r" % (t["school"], t["cut"])


def test_every_id_survives_the_format_check_in_sql(library):
    """set_my_team rejects anything else, so an id it refuses is unpickable."""
    ok = re.compile(r"^[A-Za-z0-9_-]{1,16}$")
    for t in library:
        assert ok.match(t["id"]), "%s has id %r, which set_my_team would reject" % (
            t["school"], t["id"])


def test_no_two_schools_share_an_id(library):
    ids = [t["id"] for t in library]
    assert len(ids) == len(set(ids))


# ------------------------------------------------------------------ the extras

def test_georgia_college_is_in_the_pack(library):
    """Grant's alma mater, and the reason the extras pipeline exists at all.

    It is Division II Peach Belt with no football team, so it is in none of ESPN's lists
    and nothing else in the build would notice if it disappeared.
    """
    gc = [t for t in library if t["id"] == "gcsu"]
    assert gc, "Georgia College is missing from the library"
    assert gc[0]["mascot"] == "Bobcats"
    assert gc[0]["bg"] == "#001e78", (
        "the bobcat is outlined in the school green and vanishes on green; it was put on "
        "the school navy on purpose")


def test_every_extra_school_records_where_its_mark_came_from():
    """These are copyrighted school marks. The basis for using them is not optional."""
    for t in read_json(EXTRA):
        for field in ("source", "source_page", "license"):
            assert t.get(field), "%s has no %s" % (t["id"], field)
        assert t["source"].startswith("https://"), t["id"]


# ---------------------------------------------------------------- the block colour

BUG_CHROME = (16, 21, 28)


def _lum(rgb):
    f = []
    for v in rgb:
        v /= 255.0
        f.append(v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4)
    return 0.2126 * f[0] + 0.7152 * f[1] + 0.0722 * f[2]


def _contrast(a, b):
    x, y = _lum(a) + 0.05, _lum(b) + 0.05
    return max(x, y) / min(x, y)


def _rgb(value):
    v = value.lstrip("#")
    return tuple(int(v[i:i + 2], 16) for i in (0, 2, 4))


def test_every_team_has_a_block_colour(library):
    """`alt` is what the scorebug paints behind a player's mark. A team without one falls
    back to the player's own colour, which is fine for an unclaimed seat and wrong for a
    school, so none should be missing."""
    missing = [t["abbr"] for t in library if not t.get("alt")]
    assert not missing, "no block colour for %s" % missing[:6]


def test_the_block_is_never_the_disc(library):
    """The whole reason `alt` is not simply ESPN's alt_color. Wyoming's alternate IS its
    disc, so read literally the mark would sit on its own background and the disc would
    stop existing."""
    same = [t["abbr"] for t in library if t["alt"].lower() == t["bg"].lower()]
    assert not same, "block equals disc for %s" % same[:6]


def test_every_block_reads_against_the_scorebug(library):
    """Measured, because two of the four schools on the roster carry black as their second
    colour. Kennesaw's #0b1315 scored 1.02 against the bug's #10151c chrome and Georgia's
    #2c2a29 scored 1.28: both were invisible in the harness on 2026-09-10."""
    weak = [(t["abbr"], t["alt"], round(_contrast(_rgb(t["alt"]), BUG_CHROME), 2))
            for t in library if _contrast(_rgb(t["alt"]), BUG_CHROME) < 1.65]
    assert not weak, "block would not read on the bug: %s" % weak[:6]


def test_lifting_is_recorded_and_rare(library):
    """`alt_from` says whether a colour is the school's as published or was raised off the
    chrome to be visible, so a surprising block can be explained without rerunning
    anything. It should be a minority: if most of the pack needs lifting, the target is
    wrong rather than the palettes."""
    lifted = [t for t in library if t.get("alt_from") == "lifted"]
    assert all(t.get("alt_from") for t in library), "alt_from missing on some teams"
    assert len(lifted) < len(library) / 2, (
        "%d of %d blocks had to be lifted; MIN_BLOCK_CONTRAST is probably too high"
        % (len(lifted), len(library)))
