"""The gate for the app icons.

Built 2026-09-11 when the placeholder (a green square with an orange football, left over
from the first commit and not even the app's colours any more) was replaced with Grant's
blue logo.

Everything here is a lesson from that swap. The icons are generated by
scripts/build_icons.py from inputs/app-icon.png, so the guards check the OUTPUT rather
than the script: what ships is what a phone renders.
"""
from __future__ import annotations

import json
import os
import re

import pytest

Image = pytest.importorskip("PIL.Image", reason="pip install pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "static", "icons")

EXPECTED = {"icon-180.png": 180, "icon-192.png": 192,
            "icon-512.png": 512, "icon-512-maskable.png": 512}


def load(name):
    return Image.open(os.path.join(ICONS, name)).convert("RGBA")


@pytest.mark.parametrize("name,size", sorted(EXPECTED.items()))
def test_each_icon_is_the_size_it_claims(name, size):
    im = load(name)
    assert im.size == (size, size), "%s is %s, not %dx%d" % (name, im.size, size, size)


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_no_icon_has_a_transparent_pixel(name):
    """iOS masks a home screen icon to its own squircle and composites whatever is left
    against BLACK. Source art that is already a rounded square therefore gets a dark
    halo inside Apple's curve, which is exactly what the first build of these did.

    The blue logo also made this harder to catch than it should have been: its interior
    alpha is 249 to 253, never a clean 255, so a corner test written as `== 255` found
    nothing solid anywhere and silently took the wrong code path. Hence min, not corners.
    """
    alpha = load(name).getchannel("A")
    assert min(alpha.getdata()) == 255, (
        "%s has transparency; iOS would composite it against black" % name
    )


def test_the_maskable_icon_keeps_its_art_inside_the_safe_area():
    """A maskable icon is cropped to whatever shape the launcher likes, and only the
    middle 80% is guaranteed. Its border must therefore be background, not artwork."""
    im = load("icon-512-maskable.png")
    w = im.size[0]
    corners = {im.getpixel(p)[:3] for p in ((0, 0), (w - 1, 0), (0, w - 1), (w - 1, w - 1))}
    assert len(corners) == 1, "the maskable border is not a flat fill: %s" % corners

    fill = corners.pop()
    assert fill != (255, 255, 255), (
        "the maskable border is white. build_icons filled it from the art's DOMINANT "
        "colour, which is the white M and wordmark, instead of the art's edge colour"
    )
    # And it must actually be the logo's blue rather than any flat colour that passes.
    r, g, b = fill
    assert b > r and b > g, "the maskable border is not the logo's blue: %s" % (fill,)


def test_every_icon_the_app_names_exists():
    """Walks the manifest and index.html rather than trusting the list above, so an icon
    added to either without being generated fails here instead of 404ing on a phone."""
    with open(os.path.join(ROOT, "static", "manifest.webmanifest"), encoding="utf-8") as f:
        manifest = json.load(f)
    named = {os.path.basename(i["src"]) for i in manifest["icons"]}

    with open(os.path.join(ROOT, "index.html"), encoding="utf-8") as f:
        named |= set(re.findall(r"icons/([\w.-]+\.png)", f.read()))

    assert named, "nothing references an icon at all"
    for name in sorted(named):
        assert os.path.exists(os.path.join(ICONS, name)), \
            "%s is referenced but not in static/icons/" % name


def test_the_notification_icon_is_one_that_exists():
    """static/sw.js hands these paths to showNotification. A 404 there is silent: the
    notification arrives with no icon and nothing anywhere reports it."""
    with open(os.path.join(ROOT, "static", "sw.js"), encoding="utf-8") as f:
        sw = f.read()
    used = set(re.findall(r"BASE \+ 'icons/([\w.-]+\.png)'", sw))
    assert used, "the worker names no notification icon"
    for name in sorted(used):
        assert os.path.exists(os.path.join(ICONS, name)), \
            "sw.js shows %s on a notification and it does not exist" % name


def test_the_icons_match_the_source_artwork():
    """Regenerating must be a no-op. If this fails, someone edited a PNG by hand or
    changed the source without running the script, and the two have drifted."""
    src = os.path.join(ROOT, "inputs", "app-icon.png")
    if not os.path.exists(src):
        pytest.skip("inputs/app-icon.png is not present")
    import sys
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import build_icons

    art = build_icons.opaque(build_icons.squared(
        Image.open(src).convert("RGBA").crop(
            build_icons.solid_box(Image.open(src).convert("RGBA")))))
    fresh = art.resize((512, 512), Image.LANCZOS)
    shipped = load("icon-512.png")
    assert list(fresh.getdata()) == list(shipped.getdata()), (
        "static/icons/icon-512.png does not match inputs/app-icon.png. "
        "Run python scripts/build_icons.py"
    )
