-- ============================================================================
--  Motley Pick'em: complete database setup.
--
--  Paste this whole file into the Supabase SQL Editor and press Run. Once.
--  Every statement is idempotent, so running it again is harmless.
--
--  Generated by scripts/build_combined_migration.py. Do not edit by hand;
--  edit the numbered migration it came from and regenerate.
-- ============================================================================


-- --------------------------------------------------------------------------
-- 001_init.sql

-- cfb-pickem, initial schema.
-- Paste into the Supabase SQL Editor and run once. Safe to re-run.
--
-- SECURITY MODEL
-- There is no Supabase Auth here: sign-in is a seat plus a 4-digit PIN, so there is no
-- auth.uid() for RLS to key off. Instead, every table denies direct client access and all
-- reads and writes go through SECURITY DEFINER functions that take a session token. That
-- puts the two rules that must never be client-side in exactly one place:
--   1. a pick cannot be written once its game has kicked off
--   2. you cannot see another player's pick until that game has kicked off
-- The anon key ships in the browser bundle, so anything not enforced here is not enforced.

-- pgcrypto supplies crypt, gen_salt, digest and gen_random_bytes, which hash the PINs
-- and the session tokens.
--
-- Supabase installs extensions into the `extensions` schema, not `public`. Every
-- function below therefore pins `search_path = public, extensions`. Pinning it to
-- `public` alone fails at creation with:
--     ERROR: function digest(text, unknown) does not exist
-- A SECURITY DEFINER function still needs an explicit search_path so it cannot be
-- hijacked by a caller's, so the fix is to name both schemas rather than drop the pin.
-- On a plain Postgres where pgcrypto lands in `public`, a missing `extensions` schema in
-- the search path is simply ignored, so the same line works there too.
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- tables

create table if not exists players (
  id            smallint primary key check (id between 1 and 4),
  name          text,
  pin_hash      text,
  is_admin      boolean     not null default false,
  color         text        not null,
  claimed_at    timestamptz,
  failed_tries  smallint    not null default 0,
  locked_until  timestamptz
);

create table if not exists sessions (
  token_hash  text        primary key,
  player_id   smallint    not null references players(id) on delete cascade,
  created_at  timestamptz not null default now(),
  last_seen   timestamptz not null default now()
);
create index if not exists sessions_player on sessions(player_id);

create table if not exists weeks (
  id           serial      primary key,
  season       smallint    not null,
  week_no      smallint    not null,
  label        text        not null,
  published    boolean     not null default false,
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  unique (season, week_no)
);

create table if not exists games (
  id            bigint      primary key,             -- ESPN event id
  week_id       int         not null references weeks(id) on delete cascade,
  home_id       text        not null,                -- ESPN team id, for logos
  away_id       text        not null,
  home_abbr     text        not null,
  away_abbr     text        not null,
  home_school   text,
  away_school   text,
  home_conf     int,
  away_conf     int,
  kickoff       timestamptz not null,
  neutral_site  boolean     not null default false,
  tv            text,
  spread_line   numeric(4,1),
  favorite_abbr text,
  underdog_abbr text,
  tier          text,
  interest      numeric(7,2),
  featured      boolean     not null default false,
  in_slate      boolean     not null default false,  -- true for the chosen 20
  state         text        not null default 'pre',  -- pre | in | post
  home_score    smallint,
  away_score    smallint,
  winner_abbr   text,
  status_detail text,
  updated_at    timestamptz not null default now()
);
create index if not exists games_week   on games(week_id);
create index if not exists games_slate  on games(week_id, in_slate);
create index if not exists games_kick   on games(kickoff);

create table if not exists picks (
  player_id   smallint    not null references players(id) on delete cascade,
  game_id     bigint      not null references games(id)   on delete cascade,
  week_id     int         not null references weeks(id)   on delete cascade,
  pick_abbr   text        not null,
  confidence  smallint    not null check (confidence between 1 and 20),
  auto        boolean     not null default false,
  updated_at  timestamptz not null default now(),
  primary key (player_id, game_id)
);
-- Each confidence value is spent exactly once per player per week.
create unique index if not exists picks_one_value_per_week
  on picks(player_id, week_id, confidence);
create index if not exists picks_week on picks(week_id);

-- ---------------------------------------------------------------- lock everything down

alter table players  enable row level security;
alter table sessions enable row level security;
alter table weeks    enable row level security;
alter table games    enable row level security;
alter table picks    enable row level security;

-- No policies are created on purpose. With RLS on and no policy, anon and authenticated
-- get nothing. Every legitimate path is a SECURITY DEFINER function below.
revoke all on players, sessions, weeks, games, picks from anon, authenticated;

-- ---------------------------------------------------------------- seed the four seats

insert into players (id, is_admin, color) values
  (1, true,  '#B85C1F'),
  (2, true,  '#1F6F4A'),
  (3, false, '#2E5C8A'),
  (4, false, '#8A2E4F')
on conflict (id) do nothing;

-- ---------------------------------------------------------------- helpers

create or replace function _player_for(p_token text)
returns players language sql stable security definer set search_path = public, extensions as $$
  select p.* from sessions s join players p on p.id = s.player_id
  where s.token_hash = encode(digest(p_token, 'sha256'), 'hex')
$$;

create or replace function _new_session(p_player smallint)
returns text language plpgsql security definer set search_path = public, extensions as $$
declare tok text;
begin
  tok := encode(gen_random_bytes(32), 'hex');
  insert into sessions (token_hash, player_id)
    values (encode(digest(tok, 'sha256'), 'hex'), p_player);
  return tok;
end $$;

-- ---------------------------------------------------------------- sign-in surface

-- Public. Never returns pin_hash.
create or replace function list_seats()
returns table (id smallint, name text, is_admin boolean, claimed boolean, color text)
language sql stable security definer set search_path = public, extensions as $$
  select p.id, p.name, p.is_admin, (p.name is not null), p.color
  from players p order by p.id
$$;

create or replace function claim_seat(p_seat smallint, p_name text, p_pin text)
returns text language plpgsql security definer set search_path = public, extensions as $$
declare updated smallint;
begin
  if p_pin !~ '^[0-9]{4}$' then
    raise exception 'PIN must be exactly 4 digits';
  end if;
  if length(btrim(coalesce(p_name, ''))) = 0 then
    raise exception 'Name is required';
  end if;

  -- Only an unclaimed seat can be taken. This is what stops a seat being stolen.
  update players
     set name = btrim(p_name),
         pin_hash = crypt(p_pin, gen_salt('bf')),
         claimed_at = now()
   where id = p_seat and name is null
  returning id into updated;

  if updated is null then
    raise exception 'That seat is already taken';
  end if;
  return _new_session(updated);
end $$;

create or replace function sign_in(p_seat smallint, p_pin text)
returns text language plpgsql security definer set search_path = public, extensions as $$
declare rec players;
begin
  select * into rec from players where id = p_seat;
  if rec.id is null or rec.pin_hash is null then
    raise exception 'That seat has not been claimed yet';
  end if;
  if rec.locked_until is not null and rec.locked_until > now() then
    raise exception 'Too many wrong PINs. Try again in a minute.';
  end if;

  if rec.pin_hash = crypt(p_pin, rec.pin_hash) then
    update players set failed_tries = 0, locked_until = null where id = p_seat;
    return _new_session(p_seat);
  end if;

  update players
     set failed_tries = failed_tries + 1,
         locked_until = case when failed_tries + 1 >= 5
                             then now() + interval '1 minute' else null end
   where id = p_seat;
  raise exception 'Wrong PIN';
end $$;

create or replace function whoami(p_token text)
returns table (id smallint, name text, is_admin boolean, color text)
language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  update sessions set last_seen = now()
    where token_hash = encode(digest(p_token, 'sha256'), 'hex');
  return query select me.id, me.name, me.is_admin, me.color;
end $$;

create or replace function sign_out(p_token text)
returns void language sql security definer set search_path = public, extensions as $$
  delete from sessions where token_hash = encode(digest(p_token, 'sha256'), 'hex')
$$;

-- ---------------------------------------------------------------- reads

-- The slate for a week, with my own picks attached. Other players' picks are NOT here.
create or replace function get_slate(p_token text, p_week int)
returns table (
  game_id bigint, kickoff timestamptz, locked boolean,
  home_id text, home_abbr text, home_school text, home_score smallint,
  away_id text, away_abbr text, away_school text, away_score smallint,
  neutral_site boolean, tv text, spread_line numeric, favorite_abbr text,
  underdog_abbr text, tier text, state text, status_detail text, winner_abbr text,
  my_pick text, my_confidence smallint, my_auto boolean
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  return query
    select g.id, g.kickoff, (g.kickoff <= now()),
           g.home_id, g.home_abbr, g.home_school, g.home_score,
           g.away_id, g.away_abbr, g.away_school, g.away_score,
           g.neutral_site, g.tv, g.spread_line, g.favorite_abbr,
           g.underdog_abbr, g.tier, g.state, g.status_detail, g.winner_abbr,
           pk.pick_abbr, pk.confidence, pk.auto
      from games g
      join weeks w on w.id = g.week_id and w.published
      left join picks pk on pk.game_id = g.id and pk.player_id = me.id
     where g.week_id = p_week and g.in_slate
     order by g.kickoff, g.id;
end $$;

-- Everyone's picks, but only for games that have already kicked off.
create or replace function get_board(p_token text, p_week int)
returns table (
  game_id bigint, player_id smallint, player_name text, player_color text,
  pick_abbr text, confidence smallint, auto boolean, correct boolean, points smallint
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  return query
    select g.id, pl.id, pl.name, pl.color, pk.pick_abbr, pk.confidence, pk.auto,
           case when g.winner_abbr is null then null
                else pk.pick_abbr = g.winner_abbr end,
           case when g.winner_abbr is null then null
                when pk.pick_abbr = g.winner_abbr then pk.confidence
                else 0::smallint end
      from picks pk
      join games g   on g.id = pk.game_id
      join players pl on pl.id = pk.player_id
     where pk.week_id = p_week
       and g.in_slate
       and g.kickoff <= now()          -- the visibility rule, enforced here and nowhere else
     order by g.kickoff, pl.id;
end $$;

create or replace function get_standings(p_token text)
returns table (
  player_id smallint, player_name text, player_color text,
  weeks_played bigint, correct bigint, games bigint, points bigint
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  return query
    select pl.id, pl.name, pl.color,
           count(distinct pk.week_id),
           count(*) filter (where pk.pick_abbr = g.winner_abbr),
           count(*) filter (where g.winner_abbr is not null),
           coalesce(sum(case when pk.pick_abbr = g.winner_abbr
                             then pk.confidence else 0 end), 0)
      from players pl
      left join picks pk on pk.player_id = pl.id
      left join games g  on g.id = pk.game_id and g.in_slate
     where pl.name is not null
     group by pl.id, pl.name, pl.color
     order by 7 desc, 5 desc;
end $$;

-- ---------------------------------------------------------------- writing picks

-- p_picks is [{"game_id":123,"pick":"UGA","confidence":20}, ...] for the whole slate.
-- Locked games must be submitted exactly as already stored, which makes a stale client
-- fail loudly instead of silently dropping a pick.
create or replace function save_picks(p_token text, p_week int, p_picks jsonb)
returns table (saved int, locked int) language plpgsql
security definer set search_path = public, extensions as $$
declare
  me players;
  n_slate  int;
  n_sent   int;
  n_games  int;
  n_confs  int;
  v_min    int;
  v_max    int;
  n_lock   int := 0;
  n_save   int := 0;
  r record;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;

  select count(*) into n_slate
    from games g join weeks w on w.id = g.week_id and w.published
   where g.week_id = p_week and g.in_slate;
  if n_slate = 0 then raise exception 'That week is not published'; end if;

  -- One pass over the payload for every shape check. jsonb_to_recordset is used inline
  -- rather than a temp table: a temp table created inside a function breaks plan caching
  -- on the second call in a pooled connection.
  select count(*), count(distinct i.game_id), count(distinct i.confidence),
         min(i.confidence), max(i.confidence)
    into n_sent, n_games, n_confs, v_min, v_max
    from jsonb_to_recordset(p_picks)
      as i(game_id bigint, pick text, confidence smallint);

  if n_sent <> n_slate then
    raise exception 'Expected % picks, got %', n_slate, n_sent;
  end if;
  if n_games <> n_sent then
    raise exception 'The same game was submitted twice';
  end if;
  if n_confs <> n_sent or v_min <> 1 or v_max <> n_slate then
    raise exception 'Confidence must use every value from 1 to % exactly once', n_slate;
  end if;

  if exists (
      select 1
        from jsonb_to_recordset(p_picks)
          as i(game_id bigint, pick text, confidence smallint)
        left join games g
          on g.id = i.game_id and g.week_id = p_week and g.in_slate
       where g.id is null) then
    raise exception 'A submitted game is not on this week''s slate';
  end if;

  if exists (
      select 1
        from jsonb_to_recordset(p_picks)
          as i(game_id bigint, pick text, confidence smallint)
        join games g on g.id = i.game_id
       where i.pick not in (g.home_abbr, g.away_abbr)) then
    raise exception 'A pick is not one of the two teams in that game';
  end if;

  -- Reject any attempt to change a game that has already kicked off. A stale client
  -- fails loudly here instead of silently losing a pick.
  for r in
    select i.game_id, i.pick, i.confidence,
           pk.pick_abbr, pk.confidence as old_conf
      from jsonb_to_recordset(p_picks)
        as i(game_id bigint, pick text, confidence smallint)
      join games g on g.id = i.game_id
      left join picks pk on pk.game_id = i.game_id and pk.player_id = me.id
     where g.kickoff <= now()
  loop
    n_lock := n_lock + 1;
    if r.pick_abbr is null then
      raise exception 'Game % already kicked off and has no pick to keep', r.game_id;
    end if;
    if r.pick is distinct from r.pick_abbr or r.confidence is distinct from r.old_conf then
      raise exception 'Game % is locked and cannot be changed', r.game_id;
    end if;
  end loop;

  -- Clear this week's unlocked picks, then write the new set. Both happen in the one
  -- transaction of this call, so the unique index on (player, week, confidence) never
  -- sees a half-applied reshuffle.
  delete from picks pk using games g
   where pk.player_id = me.id and pk.week_id = p_week
     and g.id = pk.game_id and g.kickoff > now();

  insert into picks (player_id, game_id, week_id, pick_abbr, confidence, auto, updated_at)
  select me.id, i.game_id, p_week, i.pick, i.confidence, false, now()
    from jsonb_to_recordset(p_picks)
      as i(game_id bigint, pick text, confidence smallint)
    join games g on g.id = i.game_id
   where g.kickoff > now();
  get diagnostics n_save = row_count;

  return query select n_save, n_lock;
end $$;

-- ---------------------------------------------------------------- auto-picks at kickoff

-- Any claimed player with no pick on a game that has started gets the UNDERDOG at the
-- lowest confidence value they have not spent that week. Run from the sync job.
create or replace function apply_auto_picks()
returns int language plpgsql security definer set search_path = public, extensions as $$
declare r record; v_conf smallint; n int := 0;
begin
  for r in
    select g.id as game_id, g.week_id, pl.id as player_id,
           coalesce(g.underdog_abbr, g.away_abbr) as dog
      from games g
      join weeks w  on w.id = g.week_id and w.published
      cross join players pl
      left join picks pk on pk.game_id = g.id and pk.player_id = pl.id
     where g.in_slate and g.kickoff <= now()
       and pl.name is not null and pk.player_id is null
     order by g.kickoff
  loop
    select min(c) into v_conf
      from generate_series(1, 20) c
     where c not in (select confidence from picks
                      where player_id = r.player_id and week_id = r.week_id);
    exit when v_conf is null;
    insert into picks (player_id, game_id, week_id, pick_abbr, confidence, auto)
      values (r.player_id, r.game_id, r.week_id, r.dog, v_conf, true)
    on conflict do nothing;
    n := n + 1;
  end loop;
  return n;
end $$;

-- ---------------------------------------------------------------- admin

create or replace function publish_slate(p_token text, p_week int, p_game_ids bigint[])
returns int language plpgsql security definer set search_path = public, extensions as $$
declare me players; n int;
begin
  me := _player_for(p_token);
  if me.id is null or not me.is_admin then
    raise exception 'Only an admin can publish the slate';
  end if;
  if array_length(p_game_ids, 1) <> 20 then
    raise exception 'A slate must be exactly 20 games, got %',
      coalesce(array_length(p_game_ids, 1), 0);
  end if;
  if exists (select 1 from games
              where id = any(p_game_ids) and week_id = p_week and kickoff <= now()) then
    raise exception 'Cannot publish a slate containing a game that already kicked off';
  end if;

  update games set in_slate = (id = any(p_game_ids)) where week_id = p_week;
  select count(*) into n from games where week_id = p_week and in_slate;
  update weeks set published = true, published_at = now() where id = p_week;
  return n;
end $$;

-- ---------------------------------------------------------------- grants

revoke all on function claim_seat(smallint, text, text)  from public;
revoke all on function sign_in(smallint, text)           from public;
revoke all on function _player_for(text)                 from public, anon, authenticated;
revoke all on function _new_session(smallint)            from public, anon, authenticated;
revoke all on function apply_auto_picks()                from public, anon, authenticated;

grant execute on function list_seats()                       to anon, authenticated;
grant execute on function claim_seat(smallint, text, text)   to anon, authenticated;
grant execute on function sign_in(smallint, text)            to anon, authenticated;
grant execute on function whoami(text)                       to anon, authenticated;
grant execute on function sign_out(text)                     to anon, authenticated;
grant execute on function get_slate(text, int)               to anon, authenticated;
grant execute on function get_board(text, int)               to anon, authenticated;
grant execute on function get_standings(text)                to anon, authenticated;
grant execute on function save_picks(text, int, jsonb)       to anon, authenticated;
grant execute on function publish_slate(text, int, bigint[]) to anon, authenticated;

-- --------------------------------------------------------------------------
-- 002_get_pool.sql

-- The commissioner's slate builder.
-- Paste into the Supabase SQL Editor after 001_init.sql. Safe to re-run.
--
-- 001 shipped without this: the Setup screen called get_pool, which existed only in the
-- local mock, so the screen worked in development and would have failed against the real
-- database. tests/test_migration.py now asserts every RPC the client calls exists here.

-- Every candidate game for a week, whether or not it made the slate. Admin only: the
-- pool reveals which games are under consideration before the week is published.
create or replace function get_pool(p_token text, p_week int)
returns table (
  game_id bigint, kickoff timestamptz, locked boolean, in_slate boolean,
  home_id text, home_abbr text, home_school text,
  away_id text, away_abbr text, away_school text,
  neutral_site boolean, tv text, spread_line numeric,
  favorite_abbr text, underdog_abbr text, tier text,
  interest numeric, featured boolean
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null or not me.is_admin then
    raise exception 'Only an admin can see the pool';
  end if;
  return query
    select g.id, g.kickoff, (g.kickoff <= now()), g.in_slate,
           g.home_id, g.home_abbr, g.home_school,
           g.away_id, g.away_abbr, g.away_school,
           g.neutral_site, g.tv, g.spread_line,
           g.favorite_abbr, g.underdog_abbr, g.tier,
           g.interest, g.featured
      from games g
     where g.week_id = p_week
     order by g.kickoff, g.id;
end $$;

revoke all on function get_pool(text, int) from public;
grant execute on function get_pool(text, int) to anon, authenticated;

-- --------------------------------------------------------------------------
-- 003_get_week.sql

-- Week metadata for the app header.
-- Paste into the Supabase SQL Editor after 002. Safe to re-run.
--
-- Week numbers follow ESPN's published college football calendar rather than a
-- Monday-to-Sunday guess. Boundaries land about 3am ET Monday, so a Thursday game
-- belongs to the week that opened the previous Monday, and Week 1 of 2026 is a
-- seventeen-day window because it absorbs Week 0. See scripts/cfb_weeks.py.

alter table weeks add column if not exists starts_at timestamptz;
alter table weeks add column if not exists ends_at   timestamptz;

create or replace function get_week(p_token text, p_week int)
returns table (
  id int, season smallint, week_no smallint, label text,
  published boolean, starts_at timestamptz, ends_at timestamptz,
  slate_size bigint
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  return query
    select w.id, w.season, w.week_no, w.label, w.published, w.starts_at, w.ends_at,
           (select count(*) from games g where g.week_id = w.id and g.in_slate)
      from weeks w
     where w.id = p_week;
end $$;

-- The week currently in progress, so the app does not have to know an id up front.
create or replace function get_current_week(p_token text)
returns table (
  id int, season smallint, week_no smallint, label text,
  published boolean, starts_at timestamptz, ends_at timestamptz,
  slate_size bigint
) language plpgsql stable security definer set search_path = public, extensions as $$
declare me players;
begin
  me := _player_for(p_token);
  if me.id is null then raise exception 'Not signed in'; end if;
  return query
    select w.id, w.season, w.week_no, w.label, w.published, w.starts_at, w.ends_at,
           (select count(*) from games g where g.week_id = w.id and g.in_slate)
      from weeks w
     where now() between coalesce(w.starts_at, '-infinity'::timestamptz)
                     and coalesce(w.ends_at, 'infinity'::timestamptz)
     order by w.season desc, w.week_no desc
     limit 1;
end $$;

revoke all on function get_week(text, int)      from public;
revoke all on function get_current_week(text)   from public;
grant execute on function get_week(text, int)    to anon, authenticated;
grant execute on function get_current_week(text) to anon, authenticated;
