"""Concatenate the migrations into one file to paste into the Supabase SQL Editor.

Running three files in order is three chances to run them out of order or miss one.
This is generated, never hand-edited: tests/test_migration.py checks it matches.

Usage:
    python scripts/build_combined_migration.py
"""
from __future__ import annotations

import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "migrations", "ALL.sql")

HEADER = """\
-- ============================================================================
--  Motley Pick'em: complete database setup.
--
--  Paste this whole file into the Supabase SQL Editor and press Run. Once.
--  Every statement is idempotent, so running it again is harmless.
--
--  Generated by scripts/build_combined_migration.py. Do not edit by hand;
--  edit the numbered migration it came from and regenerate.
-- ============================================================================

"""


def parts():
    files = sorted(glob.glob(os.path.join(ROOT, "migrations", "[0-9][0-9][0-9]_*.sql")))
    return [f for f in files if os.path.basename(f) != "ALL.sql"]


def build() -> str:
    out = [HEADER]
    for path in parts():
        name = os.path.basename(path)
        out.append("\n-- %s\n-- %s\n\n" % ("-" * 74, name))
        with open(path, encoding="utf-8") as f:
            out.append(f.read().rstrip() + "\n")
    return "".join(out)


def main() -> int:
    sql = build()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(sql)
    print("wrote %s from %d migrations (%d lines)"
          % (os.path.relpath(OUT, ROOT), len(parts()), len(sql.splitlines())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
